@echo off

SET PROJECT_NAME=switch_touchgfx
SET OUTPUT_HEX_NAME=extFlashGui

SET INTERNAL_ADDRESS_START=0x21000000
SET INTERNAL_ADDRESS_END=0x217FFFFF

SET EXT_FLASH_ADDRESS_START=0x200000
SET EXT_FLASH_ADDRESS_END=0x9FFFFF

SET EXT_FLASH_CACHE_SIZE=0x800000

exe\srec_cat.exe hex\%PROJECT_NAME%.hex -Intel -crop %INTERNAL_ADDRESS_START% %INTERNAL_ADDRESS_END% -o hex\%OUTPUT_HEX_NAME%.hex -Intel

exe\srec_cat hex\%OUTPUT_HEX_NAME%.hex -Intel -crop %INTERNAL_ADDRESS_START% %INTERNAL_ADDRESS_END% -offset -%INTERNAL_ADDRESS_START% -o hex\%OUTPUT_HEX_NAME%.hex -Intel

exe\srec_cat hex\%OUTPUT_HEX_NAME%.hex -Intel -crop 0x00 %EXT_FLASH_CACHE_SIZE% -offset %EXT_FLASH_ADDRESS_START% -o hex\%OUTPUT_HEX_NAME%.hex -Intel

echo Completed.

pause
