@echo off

SET PROJECT_NAME=switch_touchgfx

SET OUT_EXT_HEX_NAME=extFlashGui
SET OUT_INT_HEX_NAME=intFlash

SET INTERNAL_GUI_START=0x21000000
SET INTERNAL_GUI_END=0x217FFFFF

SET INTERNAL_FLASH_START=0x08000000
SET INTERNAL_FLASH_END=0x081FFFFF

SET EXT_FLASH_GUI_START=0x200000
SET EXT_FLASH_GUI_END=0x9FFFFF

SET EXT_FLASH_GUI_SIZE=0x800000

exe\srec_cat.exe hex\%PROJECT_NAME%.hex -Intel -crop %INTERNAL_GUI_START% %INTERNAL_GUI_END% -o hex\%OUT_EXT_HEX_NAME%.hex -Intel

exe\srec_cat hex\%OUT_EXT_HEX_NAME%.hex -Intel -crop %INTERNAL_GUI_START% %INTERNAL_GUI_END% -offset -%INTERNAL_GUI_START% -o hex\%OUT_EXT_HEX_NAME%.hex -Intel

exe\srec_cat hex\%OUT_EXT_HEX_NAME%.hex -Intel -crop 0x00 %EXT_FLASH_GUI_SIZE% -offset %EXT_FLASH_GUI_START% -o hex\%OUT_EXT_HEX_NAME%.hex -Intel

exe\srec_cat.exe hex\%PROJECT_NAME%.hex -Intel -crop %INTERNAL_FLASH_START% %INTERNAL_FLASH_END% -o hex\%OUT_INT_HEX_NAME%.hex -Intel

echo Completed.

pause
